commit 93714b7db795b14b26adffde30753cfda0ca4867
Author: Miss Islington (bot) <31488909+miss-islington@users.noreply.github.com>
Date:   Wed Aug 23 03:10:04 2023 -0700

    [3.11] gh-108342: Break ref cycle in SSLSocket._create() exc (GH-108344) (#108349)
    
    Explicitly break a reference cycle when SSLSocket._create() raises an
    exception. Clear the variable storing the exception, since the
    exception traceback contains the variables and so creates a reference
    cycle.
    
    This test leak was introduced by the test added for the fix of GH-108310.
    (cherry picked from commit 64f99350351bc46e016b2286f36ba7cd669b79e3)
    
    Co-authored-by: Victor Stinner <vstinner@python.org>

diff --git a/Lib/ssl.py b/Lib/ssl.py
index ced87d4069..48d229f810 100644
--- a/Lib/ssl.py
+++ b/Lib/ssl.py
@@ -1083,7 +1083,11 @@ def _create(cls, sock, server_side=False, do_handshake_on_connect=True,
                     self.close()
                 except OSError:
                     pass
-                raise notconn_pre_handshake_data_error
+                try:
+                    raise notconn_pre_handshake_data_error
+                finally:
+                    # Explicitly break the reference cycle.
+                    notconn_pre_handshake_data_error = None
         else:
             connected = True
 
